<?php

namespace It121\AddressBundle\Entity;

/**
 * OpenPostcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpenPostcodeRepository extends \Doctrine\ORM\EntityRepository
{
}
