<?php

namespace It121\AddressBundle\Entity;

/**
 * PafPostcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PafPostcodeRepository extends \Doctrine\ORM\EntityRepository
{
}
