<?php

namespace It121\LogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CallLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallLogRepository extends EntityRepository
{

    /**
     * Find today call log
     */
    public function findNumCallsByDay($day) {

        $em = $this->getEntityManager();

        $repo = $em->getRepository('LogBundle:CallLog');
        $query = $repo->createQueryBuilder('c')
            ->select('f.unit, c.inbound, COUNT(c) num')
            ->innerJoin('c.file', 'f')
            ->where('c.callDate LIKE :day')
            ->orderBy('c.callDate', 'DESC')
            ->groupBy('f.unit', 'c.inbound')
            ->setParameter('day', $day)
        ;

        return $query->getQuery()->getResult();
    }

    /**
     * Delete old call logs older than the date
     */
    public function deleteOldCallLogs($date) {

        $em = $this->getEntityManager();

        $repo = $em->getRepository('LogBundle:CallLog');
        $query = $repo->createQueryBuilder('c')
            ->delete()
            ->where('c.callDate <= :date')
            ->setParameter('date', $date." 00:00:00")
        ;

        return $query->getQuery()->getResult();
    }
}
