<?php

namespace It121\CalldevBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CalldevRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalldevRepository extends EntityRepository
{

}