<?php

namespace It121\CalldevBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiveRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiveRecordRepository extends EntityRepository
{
    public function getOutcomes($date_from, $date_to) {

        $outcomes = $this->createQueryBuilder('r')
            ->select('SUBSTRING( r.origurn, 1, 3 ) as prefix, r.exit as outcome, COUNT(r) as num')
            ->where('DATE(r.lastcall) >= :date_from AND DATE(r.lastcall)<=:date_to')
            ->groupBy('prefix, outcome')
            ->setParameter('date_from', $date_from)
            ->setParameter('date_to', $date_to)
            ->getQuery()
            ->getArrayResult();
//            ->slice($offset, $limit);

        return $outcomes;

    }

}