backend_homepage:
    path:     /hello
    defaults: { _controller: "BackendBundle:Default:index" }

user:
     resource: "@BackendBundle/Resources/config/routing/user.yml"
     prefix:   /user

server:
     resource: "@BackendBundle/Resources/config/routing/server.yml"
     prefix:   /server
     
project:
     resource: "@BackendBundle/Resources/config/routing/project.yml"
     prefix:   /project    

projectgroup:
     resource: "@BackendBundle/Resources/config/routing/projectgroup.yml"
     prefix:   /projectgroup

address:
     resource: "@BackendBundle/Resources/config/routing/address.yml"
     prefix:   /address