imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator: { enabled: false }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name:        "%sessid_name%"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        project: "%project%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            121sys:
                driver:   "%database_driver_121sys%"
                host:     "%database_host_121sys%"
                port:     "%database_port_121sys%"
                dbname:   "%database_name_121sys%"
                user:     "%database_user_121sys%"
                password: "%database_password_121sys%"
                charset:  UTF8
            uk_postcodes:
                driver:   "%database_driver_uk_postcodes%"
                host:     "%database_host_uk_postcodes%"
                port:     "%database_port_uk_postcodes%"
                dbname:   "%database_name_uk_postcodes%"
                user:     "%database_user_uk_postcodes%"
                password: "%database_password_uk_postcodes%"
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    LogBundle: ~
                    ServerBundle: ~
                    ProjectBundle: ~
                    UserBundle: ~
            121sys:
                connection: 121sys
                mappings:
                    CallSysBundle: ~
            uk_postcodes:
                connection: uk_postcodes
                mappings:
                    AddressBundle: ~


# Parameters (global vars)
parameters:
    environment.development: "Development"
    environment.test: "Test"
    environment.acceptance: "Acceptance"
    environment.production: "Production"
    

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }
    request: { converters: true }

fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: false
#    format_listener:
#        rules:
#            - { path: ^/api, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: false }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY


nelmio_api_doc:
    name: API

services:
    pafPostcode.listener:
        class: It121\AddressBundle\EventListener\PafPostcodeListener
        calls:
            - [ setPostcodeIoAPIService, [@service_container]]
        tags:
            - { name: doctrine.event_listener, event: onFlush, method: onFlush, connection: uk_postcodes }