address:
    resource: "@AddressBundle/Resources/config/routing.yml"
    prefix:   /

call_sys:
    resource: "@CallSysBundle/Resources/config/routing.yml"
    prefix:   /

log:
    resource: "@LogBundle/Resources/config/routing.yml"
    prefix:   /

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /

server:
    resource: "@ServerBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /admin/

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard/

index:
    path: /
    defaults: { _controller: "FrameworkBundle:Redirect:redirect", route: dashboard_homepage }

login:
    path: /login
    defaults: { _controller: "BackendBundle:User:login" }
    
login_check:
    path: /login_check
    
logout:
    path: /logout

#########
#REST API
#########

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

AppointmentBundle_api:
    resource: "@AddressBundle/Controller/AddressRestController.php"
    type:     rest
    prefix:   /api