security: 
    firewalls:
        secured_area:
            pattern:    ^/*
            anonymous:  ~
            form_login: 
                login_path:  login
                check_path:  login_check
                use_referer: true
                # default_target_path: /dashboard
            logout:
                path: logout
            remember_me:
                key:      fsb1234
                lifetime: 3600

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard/data/*, roles: [ROLE_ADMINISTRATOR] }
        - { path: ^/dashboard/*, roles: [ROLE_ADMINISTRATOR, ROLE_USER] }
        - { path: ^/admin/*, roles: [ROLE_ADMINISTRATOR] }
        # You can use a regular expression for the languges '[a-z]{2}'
    
    providers:
        users:
            entity: { class: It121\UserBundle\Entity\User, property: login }
    
    encoders:
        It121\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
