<?php

namespace It121\ServerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends EntityRepository
{
	
	/**
	 * Get the Query to find all the servers by a type
	 *
	 * @param ServerType $type Get the servers  by a type
	 *
	 * @return array Servers
	 */
	public function findServersByTypeQuery($type)
	{
		$eManager = $this->getEntityManager();
	
		$query = $eManager->createQueryBuilder()
		->select('s')
		->from('ServerBundle:Server', 's')
		->innerJoin('s.type', 't')
		->where('t.name = :type')
		->orderBy('s.subtype', 'ASC')
		->setParameter('type', $type)
		;
	
		return $query;
	}
	
	/**
	 * Get the websites
	 * 
	 */
	public function findWebsites() {
		
		$entityManager = $this->getEntityManager();
		
		//Get the website type
		$websiteType = $entityManager->getRepository('ServerBundle:ServerType')->findOneBy(array(
				'name' => 'Website'
		));
		
		//Get the websites
		return $entityManager->getRepository('ServerBundle:Server')->findBy(array(
				'type' => $websiteType->getId()
		));
	}
	
	/**
	 * Get the services
	 *
	 */
	public function findServices() {
	
		$entityManager = $this->getEntityManager();
	
		//Get the website type
		$websiteType = $entityManager->getRepository('ServerBundle:ServerType')->findOneBy(array(
				'name' => 'Service'
		));
	
		//Get the websites
		return $entityManager->getRepository('ServerBundle:Server')->findBy(array(
				'type' => $websiteType->getId()
		));
	}
	
	/**
	 * Get the servers
	 *
	 */
	public function findServers() {
	
		$entityManager = $this->getEntityManager();
	
		//Get the website type
		$websiteType = $entityManager->getRepository('ServerBundle:ServerType')->findOneBy(array(
				'name' => 'Server'
		));
	
		//Get the websites
		return $entityManager->getRepository('ServerBundle:Server')->findBy(array(
				'type' => $websiteType->getId()
		));
	}
	
	
}
