user:
    path:     /
    defaults: { _controller: "BackendBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "BackendBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "BackendBundle:User:create" }
    requirements: { _method: post }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:User:update" }
    requirements: { _method: post|put }

user_password:
    pattern:  /{id}/changepass
    defaults: { _controller: "BackendBundle:User:changePassword" }

user_remove:
    path:     /{id}/remove
    defaults: { _controller: "BackendBundle:User:remove" }
    
user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:User:delete" }
    requirements: { _method: post|delete }
