<?php

namespace It121\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	
	/**
	 * Get All ordered by subtype
	 *
	 *
	 * @return array Projects
	 */
	public function findAllWithServer(){
	
		$eManager = $this->getEntityManager();
	
		$query = $eManager->createQueryBuilder()
		->select('p')
		->from('ProjectBundle:Project', 'p')
		->innerJoin('p.server', 's')
		->innerJoin('s.subtype', 'st')
		->orderBy('st.id', 'ASC')
		;
	
		$project_ar = $query->getQuery()->getResult();
	
		return $project_ar;
	}
}
