<?php

namespace It121\CronjobsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CronjobsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronjobsRepository extends EntityRepository
{

}