<?php

namespace It121\CallSysBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CallLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallLogRepository extends EntityRepository
{

    /**
     * Delete old call logs older than the date
     */
    public function deleteOldCallLogs($date) {

        $em = $this->getEntityManager();

        $repo = $em->getRepository('CallSysBundle:CallLog');
        $query = $repo->createQueryBuilder('c')
            ->delete()
            ->where('c.callDate <= :date')
            ->setParameter('date', $date." 00:00:00")
        ;

        return $query->getQuery()->getResult();
    }
}